export const SEARCH_INPUT_FOCUS = 'header/SEARCH_INPUT_FOCUS'
export const ENTER_SEARCH_LIST = 'header/TOGGLE_SEARCH_LIST'
export const CHANGE_SEARCH_LIST = 'header/CHANGE_SEARCH_LIST'
export const CHANGE_SEARCH_LIST_PAGE = 'header/CHANGE_SEARCH_LIST_PAGE'
